### PR TITLE
Us6 Explore Application with other languages

### LINKED ISSUE #25: US6A: As a user, I want to be able to explore the application using different languages so that I can use it in my native language.
Support three primary languages for the first release of ConPass namely English, French and Spanish. Also, the application should detect your default phone’s language setting and adapt the application’s language to it.

### PR DESCRIPTION
**Pull request by eufekt**
- Implement localization of language
- Implement language setting
- Add React-navigation for side Menu
- Add Redux for global state-management

### CODE REVIEW

**Comment by trevornag** [comment]
Really Good. I am super impressed and the code is clean too. However, I do receive a warning since I think the lifecycle hooks for React Native are changing or being deprecated. Other than that looks really nice and I am starting to see the mockups come to life

**Review by trevornag — APPROVED** [review]

**Comment by mohhef** [comment]
The code is clean, functionality works.
I get two yellow bar errors:

Is this behavior expected?

Screenshot_20200229-012740_Expo

**Review by mohhef — APPROVED** [review]
Since the yellow bar issues are not a problem as addressed, I think it's ready to be merged.

**Review by h-karim — APPROVED** [review]
As far as I can see, everything works well. Burger menu is responsive, we'll eventually have to see get rid of the warnings.

**Pull request merged**
