### PR TITLE
Enhancement - Help Page

### LINKED ISSUE #139: Enhancement - Build Help Page
Help Page should look like the following Mock

### PR DESCRIPTION
**Pull request by GD-Dheer**
Complete Help Page matching UI with DropDown functionality

image

### CODE REVIEW

**Comment by laithAwad** [comment]
I have reviewed the help page and it seems to be working fine.

**Review by gisellemartel — CHANGES_REQUESTED** [review]
IMG_3DBADCC235D8-1
testing feature and it works as intended. However, on my device the styling looks a little strange:

**Review by gisellemartel — APPROVED** [review]
Looks good! Help page works as expected and formatting issues are fixed

**Review by mohhef — CHANGES_REQUESTED** [review]
Works well.

**Review by mohhef — APPROVED** [review]

**Review by sebhani — COMMENTED** [review]
The headline (Topics) is cropped on my phone. I use Galaxy Note 5, OS Version: Android 7.0.

Screenshot_20200418-094148

**Comment by eufekt** [comment]
@GD-Dheer please make sure that the whole page translates and so does the back button. Thanks
The functionality works

**Review by trevornag — APPROVED** [review]
Works!

**Pull request merged**
