### PR TITLE
Bug 13&14 calendar crash

### LINKED ISSUE #145: Bug-10 List of suggestion shows up when choosing a location in the first search bar and setting a path
**Environment**
Phone: Note 9
OS Version: 10

**Steps to reproduce**

- Load the application in expo
- Select a location from the search bar
- Press on the lower right button to set a path

**Expected behavior**
A path should be drawn from the location chosen to the current location and no list is shown

**Current behavior**
A path is drawn from the location chosen to the current location and a list is shown

### LINKED ISSUE #159: Bug-13 Calendar feature crashes
**Environment**

Phone: iPhone 
iOS version: 11.4.1

**Steps to reproduce**
1 - Click on the burger menu
2 - Click on calendar

**Current behavior**

Crashes completely with the error message seen in the screen capture below

**Expected behavior**

Allow the user to login to their google account in order for the calendar's features to work

**Screenshots**

### LINKED ISSUE #161: [#12] Bug -14 Getting directions from calendar crashes
**Environment**

Phone: Note 9
OS Version: 10

**Steps to reproduce**

1 - Click on the burger menu
2 - Click on calendar
3 - Choose an event with a direction description
4 - Press on getdirections

**Current behavior**

Crashes completely with the error message seen in the screen capture below

**Expected behavior**

Allow the user to get directions to the target location

**Screenshots**
Screenshot_20200418-124854_Expo

### PR DESCRIPTION
**Pull request by trevornag**
This is an emergency HIGH PRIORITY bug fix. The calendar feature should work as was tested previously. No code was changed just a little verification and renaming of a method in a test (not relevant to the fix). Please verify that the calendar feature works without crashing the application.

To test: Go through bug 13,14 & 10 and make sure they are cannot be reproduced
Summary of what to test
1. Click on the Calendar link from the burger menu (this should work and not crash)
2. From a calendar event you should be able to get directions (path drawn)
3. Once path is drawn , make sure  that the suggestions disappear from view

### CODE REVIEW

**Comment by trevornag** [comment]
Thank you @sebhani and @t98b for investigating the problem with me.

**Review by sebhani — APPROVED** [review]
Doesn't crash anymore.

**Comment by gisellemartel** [comment]
Please clarify in the PR title and description which bugs are being addressed and the testing criteria.

**Review by GD-Dheer — COMMENTED** [review]
Verified each bug individually and component no longer crashes. Calendar component does produce a memory leak warning that should be addressed - happens when you log out. Finally a minor styling issue, the back button seems to be a different colour than the rest of the page. 

IMG_F2CA4CFB9E77-1

**Comment by mohhef** [comment]
@GD-Dheer  Can you verify when does the memory leak happen?

**Comment by mohhef** [comment]
@GD-Dheer Me and @t98b  have spent almost 5 hours yesterday looking for the memory leak, however, we were not able to find any leaks. This leak has been there even on master.

**Comment by GD-Dheer** [comment]
> @GD-Dheer Me and @t98b have spent almost 5 hours yesterday looking for the memory leak, however, we were not able to find any leaks

Approving as it does not cause the app to crash!

**Review by GD-Dheer — APPROVED** [review]

**Review by Belize22 — APPROVED** [review]
Bug is fixed and code changes do not violate code quality standards.

**Pull request merged**
