### PR TITLE
US2E-Select mode of transportation

### LINKED ISSUE #17: US2E: As a user, I want to be able to choose my method of transportation.
The transportation methods include by foot, by car, by public transportation including services provided by STM, Uber, and/or taxi, by bike and by Concordia’s Shuttle Service

### PR DESCRIPTION
**Pull request by trevornag**
- Buttons for bike, car, bus, walk are clickable
- Path will be adjusted depending on what the user clicks
- Unit test fixed!

### CODE REVIEW

**Review by GD-Dheer — APPROVED** [review]
Code is verified and looks clean. Buttons execute correct behaviour. Tests are all passing

**Comment by trevornag** [comment]
Note: If you notice that while running the tests you get errors in the console, this is normal because of some console.errors in the code and us testing edge cases

**Review by gisellemartel — APPROVED** [review]
Tested on iOS, feature works really well! Code looks good, well done!

**Review by eufekt — APPROVED** [review]
works properly, approved.

**Pull request merged**
