### PR TITLE
US4A: As a user, I want to be able to view the buildings interior

### LINKED ISSUE #19: US4A: As a user, I want to be able to view the buildings interior.
Should have view of floors in each building for which a floor plan in available. User should be able to switch easily between floors of building.

### PR DESCRIPTION
**Pull request by gisellemartel**
Indoor view inside campus buildings. For the moment, indoor view is supported for the following buildings:

H
MB
VE
VL

Room numbers and details of each floor are part of US4D. For now, only H8 view has details. 

To test, simply tap on the building for which you would like to see an indoor view.

Note that the UI styling is not finalized. Will be worked on in US4D

### CODE REVIEW

**Review by TalalBazerbachi — CHANGES_REQUESTED** [review]
exiting interior mode is not really intuitive, it's not really clear where to press at first.

**Comment by gisellemartel** [comment]
@t98b please note that the UI will be updated in US4D. This includes the button to exit from interior mode. This PR is purely to test functionality

**Review by TalalBazerbachi — APPROVED** [review]

**Review by Belize22 — APPROVED** [review]
Respects acceptance criteria and provides a good setup so that US4D and US4B can be worked on with a minimal amount of setup content.

**Review by mohhef — CHANGES_REQUESTED** [review]
The functionality for viewing the interior of the building works very well
1. Buttons for setting the path, and recentering the location disappeared on android.
2. The highlight on the buildings is now black borders

Screenshot_20200324-035403_Expo
Are these expected?

**Review by trevornag — APPROVED** [review]

**Comment by trevornag** [comment]
Sorry. Yes, I can confirm Mohamed's  first point about the buttons for setting the path, and re-centering the location are no longer there. I am on iPhone

**Review by trevornag — CHANGES_REQUESTED** [review]
Sorry. Yes, I can confirm Mohamed's first point about the buttons for setting the path, and re-centering the location are no longer there. I am on iPhone

**Comment by gisellemartel** [comment]
Sorry about that, it appears that my latest merge from master removed the buttons for setting path. I will revert and rebase.

**Review by trevornag — APPROVED** [review]

**Review by mohhef — APPROVED** [review]

**Pull request merged**
