### PR TITLE
Add initial react-native setup

### LINKED ISSUE #1: Boilerplate setup for React Native
Setting up the new project

### PR DESCRIPTION
**Pull request by eufekt**
- Add boiler plate to react-native application
- Configure src/components folder to have package.json file with "name" to reference this folder absolutely.
- Add Hello-World view

### CODE REVIEW

**Comment by trevornag** [comment]
Thank you @Nichita-Hariton for fixing the naming convention to adhere to the contributing guidelines. I will double check the functionality of it ASAP!

**Comment by gisellemartel** [comment]
Works great! I added the ESLinter extension and its dependencies to the branch

**Review by gisellemartel — APPROVED** [review]

**Comment by trevornag** [comment]
The application runs! And the linter works...
NOTE: On Windows run **yarn run lint --fix** otherwise you will get a lot of linebreak errors because macs and linux read linebreaks differently
image

**Review by trevornag — APPROVED** [review]

**Review by Belize22 — APPROVED** [review]
Works good when following the steps provided in the readme, although the readme should contain yarn run lint --fix for running the linter on windows so replicating the proper steps is easier.

**Pull request merged**
