### PR TITLE
splash screen added

### PR DESCRIPTION
**Pull request by laithAwad**
I have created a splash screen by editing the logo and adding a compass to be inside the letter O in our logo.

### CODE REVIEW

**Review by Belize22 — APPROVED** [review]
Works good on Android.

**Comment by TalalBazerbachi** [comment]
@laithAwad  the splash screen looks good, can you also change the logo that is in the side menu to the new logo

**Review by trevornag — CHANGES_REQUESTED** [review]
I think we should hold off on merging this, as this is not priority and we need to validate that it does not interfere with the apk generation (since images are sent to the expo server, compressed and processed and it should not be a problem but we need to validate it).

**Comment by laithAwad** [comment]
I have changed the logo in the side menu as well to be the same, and @trevornag it already load from an empty box shaped image now for the splash screen, I changed that to a new image I don't think it will affect anything, but you can validate it whenever you have time, it is all ready here.

**Comment by trevornag** [comment]
@laithAwad ok. Well I would prefer higher priority changes be merged to master first then we can test this. Also, I think the logo should appear as the app logo for when the apk is loaded onto a device. 
Additionally, a side note, when a PR is opened, it should be linked to issues (in this case #3 ) and related commits should be prepended with this reference. This is what we started doing since sprint 1. Please refer to the CONTRIBUTING.md file in the root of the project. Thank you

**Review by mohhef — APPROVED** [review]

**Review by trevornag — APPROVED** [review]

**Pull request merged**
