### PR TITLE
US4E & US4F

### LINKED ISSUE #22: US4E: As a user, I want to be able to select/specify start and end rooms to and from any floor.
Directions from Start and Endpoints include specific locations, on different floors

### LINKED ISSUE #24: US5B: As a user,  I want to get map directions to external points of interest.
Start and Finish points include external Points of Interest

### LINKED ISSUE #123: US4F - Indoor Directions from SGW to Loyola
implement a module which allows a user to obtain direction from any campus building to another campus building, including between SGW and Loyola. 

Acceptance Criteria:

- [ ] be able to get direction from one building to another on same campus (starting from inside floor plan)
- [ ] be able to get direction from one building to another on different campus (starting from inside floor plan)

### LINKED ISSUE #124: US4E - Make contextual search bar to find classrooms and indoor points of interest
Implement contextual search bar so that a starting point and destination point can be set for indoor directions

### LINKED ISSUE #126: US4E - contextual indoor directions
implement module and UI that generates indoor directions based on contextual start and end point from search bar

### PR DESCRIPTION
**Pull request by gisellemartel**
Test the following functionalities:

US4E: 
- be able to search for indoor or outdoor destination from outside
- be able to search for indoor or outdoor origin from outside
- be able to search for indoor origin (same floor and building) from inside
- be able to search for indoor or outdoor destination from inside

US4F
- be able to have directions from outdoor to outdoor point
- be able to have directions from outdoor to indoor point
- be able to have directions from indoor to indoor point (same floor)
- be able to have directions from indoor to indoor point (different floor same building)
- be able to have directions from indoor point to outside to indoor point (one building to another building)
- be able to have directions from inside (any floor) to outside point

Note that unit tests are WIP

### CODE REVIEW

**Review by TalalBazerbachi — CHANGES_REQUESTED** [review]
The 'view interior' button is overlapping with the buildingInfoModal component.
IMG_1E54B3D12990-1

**Review by mohhef — DISMISSED** [review]
There is an issue when setting the start and the destination points from the interior view where you can only choose the first option from the dropdown list.

This is probably something with the z-index.

**Review by mohhef — APPROVED** [review]
US4E:

- **be able to search for indoor or outdoor destination from outside:** works
- **be able to search for indoor or outdoor origin from outside:** works
- **be able to search for indoor origin (same floor and building) from inside:** works
- **be able to search for indoor or outdoor destination from inside:** works

US4F



- **be able to have directions from outdoor to outdoor point**: works
- **be able to have directions from outdoor to indoor point**: works
- **be able to have directions from indoor to indoor point (same floor)** : works
- **be able to have directions from indoor to indoor point (different floor same building)** : works 
- **be able to have directions from indoor point to outside to indoor point (one building to another building)** : Only works when you are in  the main map view, doesnt work if you are in the interior view
- **be able to have directions from inside (any floor) to outside point**: works

The effort and work that has went into this very much appreciated by every member who participated in this user-story

**Review by TalalBazerbachi — APPROVED** [review]

**Review by sebhani — APPROVED** [review]
It working fine for me. I noticed that the search bar when i'm in the indoor mode should be moved up similar to the outdoor one: 

Screenshot_20200418-090445

I expected to get a guide on how to use the indoor maps when I clicked on the exclamation mark, but i got information about the current building. So, if you have anyway for removing such a confusion, would be perfect.

Thank you guys!

**Pull request merged**
